/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2024.2.2503210206_sp1
    Soft IP Version: 1.0.0
    2025 06 25 14:02:35
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module sysclk_rst_gen1 (dut_clk_i, dut_rst_i, dut_clk_o, dut_rst_o, tb_rst_o,
    tb_clk_o)/* synthesis ORIG_MODULE_NAME="sysclk_rst_gen1" */ /* synthesis LATTICE_IP_GENERATED="1" */;
    input  dut_clk_i;
    input  dut_rst_i;
    output  dut_clk_o;
    output  dut_rst_o;
    output  tb_rst_o;
    output  tb_clk_o;
    SysClk_Rst_GenMon #(.DUT_CLK_IN_EN(1),
        .DUT_RST_IN_EN(1),
        .TB_CLK_PERIOD(55),
        .TB_CLK_DUTY(50),
        .TB_RST_POL(0),
        .TB_RST_PERIOD(50),
        .INIT_RST(1))
    SysClk_Rst_GenMon_inst(.dut_clk_i(dut_clk_i),
        .dut_rst_i(dut_rst_i),
        .dut_clk_o(dut_clk_o),
        .dut_rst_o(dut_rst_o),
        .tb_rst_o(tb_rst_o),
        .tb_clk_o(tb_clk_o));
endmodule