#-- Lattice Semiconductor Corporation Ltd.
#-- Bitgen run script generated by Radiant

set ret 0
if {[catch {

sys_set_attribute -gui on -msg {C:/fpga/my_soc/promote.xml}
msg_load {C:/fpga/my_soc/promote.xml}
des_set_project_udb -in {my_soc_impl_1.udb} -milestone bit -pm jd5s00
# bitgen option
bit_set_option { enable_early_io_wakeup false output_format "binary"   ip_evaluation false register_initialization true bitstream_mode normal }
#-- write result file
bit_generate -w {C:/fpga/my_soc/impl_1/my_soc_impl_1}

} out]} {
   puts $out
   set ret 1
}

exit -force ${ret}
