#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

sys_set_attribute -gui on -msg {C:/lattice-fpga/HW/promote.xml}
msg_load {C:/lattice-fpga/HW/promote.xml}
des_set_project_udb -in {HW_impl_1_syn.udb} -out {HW_impl_1_map.udb} -milestone map -pm jd5s00
des_set_reference_udb -clean
map_set_option {pdc_file "C:/lattice-fpga/HW/HW.pdc"}
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false infer_gsr false  ignore_constraint_errors false}
map_run

} out]} {
   puts $out
   set ret 1
}
exit -force ${ret}
